title: 비트코인 코리아 BitcoinKR
email: admin@bitcoinkr.org
description: >-
  비트코인 코리아. Bitcoin Korea.  비트코인 자료 번역 칼럼 커뮤니티. 라이트닝 네트워크, 작업증명, 환경, 채굴, 논문
baseurl: ""
url: "https://bitcoinkr.org"
twitter_username: bitcoinkrorg

# Build settings
markdown: kramdown
permalink: "/:categories/:year/:title:output_ext"
paginate: 80
paginate_path: "page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-crosspost-to-medium

collections:
  tags:
    output: true
    permalink: tags/:path/
